import { Inter } from 'next/font/google';
import './globals.css';
import global from './globalsStyle.css';
import { UserProvider } from '@/components/UserProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + global.body}>
        <UserProvider>{children}</UserProvider>{' '}
      </body>
    </html>
  );
}
